version: "3.1"

services:
  chat_app:
    build: .
    image: chat_app_image
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - 27017:27017
